import { refsEl } from '../src/partials/refs.js';
import { calendarTools } from './partials/calendar';
import { loadWeatherDate } from './partials/weather';
import { fetchPopularNews } from './partials/try_api';
import { apiFetchNewsByValue } from './partials/apiFetchNewsByValue';
import { changeTheme, addDarkClassToHTML } from './partials/theme-toggle';
import { toggleMenu } from './partials/mobile-version';
// import {} from './partials/categories.js';
import { apiCategoties } from './partials/api-categories';
import * as articles from './partials/articles';
// import {} from './partials/paginations';
